### ISSUE TITLE
Improve the Base model

### ISSUE THREAD

**Issue by vishwarajanand** [elliotwaite/pytorch-to-javascript-with-onnx-js#1]
Hi, I forked this repo and renamed `full-demo` to `docs` folder so that i could host it on pages.

Here is the URL I tried: https://vishwarajanand.github.io/pytorch-to-javascript-with-onnx-js/

The base model is actually way more basic than it needs to be. It doesn't detect basic hand drawn numbers, which are often confusing. Sharing a few examples of the same below.

Why I opened this issue?

> Because there's no way for me to know (easily) whether these issues are coming up due to the base model or `onnx.js` has caused these behaviors?

| Expected Number vs Predicted Number | Snap |
| ------------- | ------------- |
| 8 vs 0  | <img width="604" alt="Screenshot 2022-04-18 at 10 47 24" src="https://user-images.githubusercontent.com/7369612/163759227-319c366b-f132-48b0-9bc5-09c189e8a4ae.png">  |
| 7 vs 1  | <img width="206" alt="Screenshot 2022-04-18 at 10 52 04" src="https://user-images.githubusercontent.com/7369612/163759234-87198423-f551-48c2-af8f-9f7bc0e5aea3.png"> |
| 6 vs 5 | <img width="189" alt="Screenshot 2022-04-18 at 10 52 39" src="https://user-images.githubusercontent.com/7369612/163759247-76fec853-1766-4197-a53b-356d716c6173.png">  |
| 8 vs 0  | <img width="197" alt="Screenshot 2022-04-18 at 10 53 23" src="https://user-images.githubusercontent.com/7369612/163759248-c0715ba3-3cb0-4950-b1dd-dbbb160a2f78.png">  |
| 8 vs 5  | <img width="187" alt="Screenshot 2022-04-18 at 10 53 34" src="https://user-images.githubusercontent.com/7369612/163759249-e005e323-8a7e-4d3f-acb7-99e4f164f547.png">  |
| 9 vs 5  | <img width="189" alt="Screenshot 2022-04-18 at 10 53 52" src="https://user-images.githubusercontent.com/7369612/163759250-a6d02de0-a8ef-4ba2-ab6d-cf9e2b0b8d19.png">  |
| 6 vs 5  | <img width="186" alt="Screenshot 2022-04-18 at 10 54 04" src="https://user-images.githubusercontent.com/7369612/163759252-9d32b2f1-7e68-4c9f-913d-05f13d164a1a.png">  |
| 4 vs 0  | <img width="189" alt="Screenshot 2022-04-18 at 10 54 14" src="https://user-images.githubusercontent.com/7369612/163759253-6133431f-23fe-4ced-a793-8fa6338a2bfc.png">  |
| 4 vs 0  | <img width="182" alt="Screenshot 2022-04-18 at 10 54 22" src="https://user-images.githubusercontent.com/7369612/163759254-1a7abf11-c30f-4afd-af34-d74ab2ed8006.png">  |
| 2 vs 3  | <img width="182" alt="Screenshot 2022-04-18 at 10 55 09" src="https://user-images.githubusercontent.com/7369612/163759256-48edfdef-3ca5-4bd7-a45b-049dde1fc9de.png">  |

**Comment by elliotwaite** [comment]
Thanks for opening this issue. The poor model accuracy is due to the model being very basic. The fact that it's being run with ONNX.js rather than PyTorch should not affect its predictions. The demo is only meant to be a proof of concept so I wanted to keep the model simple, so I just used the same model that was used in [PyTorch's MNIST example](https://github.com/pytorch/examples/blob/main/mnist/main.py). But since others may also be wondering about the poor performance, I've added a note about this to the [README](https://github.com/elliotwaite/pytorch-to-javascript-with-onnx-js#live-demo-and-code-sandbox) that references this issue.

Also, if you wanted to try using a better model in your forked version, I could add a link in the README to your GitHub Pages demo so that others could also try it out.

Let me know if this resolves the issue for you, or if you think there's a better solution.

**Comment by vishwarajanand** [comment]
Thanks @elliotwaite. I was just evaluating the webpage response times with the provided onnx model.   Since you commented that the reason for poor predictions is the base model itself, rather than `onnx`, we can close out this issue.
Creating a new model for myself is a bit stretched goal for me.

**Comment by elliotwaite** [comment]
Okay, sounds good.
